### ISSUE TITLE
Move Repo to new home (github.com/kafka-rust)

### ISSUE THREAD

**Issue by johnward** [kafka-rust/kafka-rust#187]
@spicavigo - Would it be possible for your to transfer the repo to github.com/kafka-rust, so in the settings transfer it to the organistion 'kafka-rust'. I've discussed with @dead10ck and we think it is a good idea, I will add you both to the organsation. This will help encourage the community to contribute to it.

**Comment by spicavigo** [comment]
I get the following error:
You don’t have the permission to create public repositories on kafka-rust

**Comment by johnward** [comment]
I’ve added you and Skyler as a member to the organisation.

**Comment by johnward** [comment]
It would be really great if we can get this sorted. I then plan to write some articles to promote the project. Thank you so much in advance.

**Comment by spicavigo** [comment]
I tried again and same error

**Comment by johnward** [comment]
It was because you didn't accept my invitation to the kafka-rust organisation. I tried a test repo and it tranfered immidiately. I will send you another invitation. thanks

**Comment by johnward** [comment]
The repo has now moved to https://github.com/kafka-rust/kafka-rust. I'm excited to take it forward. Thank you :-)
