### ISSUE TITLE
Fix Integration Tests due to SSL certificate

### ISSUE THREAD

**Issue by johnward** [kafka-rust/kafka-rust#195]
Fix the following tests: 

test_kafka_client_load_metadata 
test_produce_fetch_messages  
test_commit_offset  
test_commit_offsets 
test_consumer_poll 
test_consumer_commit_messageset_no_consumes

This was broken due to the dependency and Rust upgrade

See this commit: https://github.com/kafka-rust/kafka-rust/commit/4e34584b6cf3fd0ddf950296c2211734bb94c108

**Comment by dead10ck** [comment]
@johnward running the tests locally worked fine for me. What issue were you seeing?

**Comment by johnward** [comment]
The SSL certificate is not set up localling so causes the secure mode to fail.

Running tests with KAFKA_VER=0.9.0.1, SCALA_VER=2.11, KAFKA_CLIENT_COMPRESSION=NONE, KAFKA_CLIENT_SECURE=secure

Need to check how the SSL certificates are set up for the Kafka docker image.


running 12 tests
test integration::client::test_commit_offset ... FAILED
test integration::client::test_commit_offsets ... FAILED
test integration::client::test_kafka_client_load_metadata ... FAILED
test integration::client::test_produce_fetch_messages ... FAILED
test integration::consumer_producer::consumer::test_consumer_commit_messageset ... FAILED
test integration::consumer_producer::consumer::test_consumer_commit_messageset_no_consumes ... FAILED
test integration::consumer_producer::consumer::test_consumer_non_existent_topic ... FAILED
test integration::consumer_producer::consumer::test_consumer_poll ... FAILED
test integration::consumer_producer::producer::test_producer_send ... FAILED
test integration::consumer_producer::producer::test_producer_send_all ... FAILED
test integration::consumer_producer::producer::test_producer_send_all_non_existent_topic ... FAILED
test integration::consumer_producer::producer::test_producer_send_non_existent_topic ... FAILED

failures:

---- integration::client::test_commit_offset stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorStack([Error { code: 336245135, library: "SSL routines", function: "SSL_CTX_use_certificate", reason: "ee key too small", file: "../ssl/ssl_rsa.c", line: 310 }])', tests/test_kafka.rs:116:44
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /home/john/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: test_kafka::integration::get_security_config
             at ./tests/test_kafka.rs:116:9
   5: core::ops::function::FnOnce::call_once
             at /home/john/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   6: core::result::Result<T,E>::and_then
             at /home/john/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:708:22
   7: test_kafka::integration::new_security_config
             at ./tests/test_kafka.rs:105:14
   8: test_kafka::integration::new_kafka_client
             at ./tests/test_kafka.rs:79:57
   9: test_kafka::integration::new_ready_kafka_client
             at ./tests/test_kafka.rs:70:26
  10: test_kafka::integration::client::test_commit_offset
             at ./tests/integration/client/mod.rs:169:22
  11: test_kafka::integration::client::test_commit_offset::{{closure}}
             at ./tests/integration/client/mod.rs:167:1
  12: core::ops::function::FnOnce::call_once
             at /home/john/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by dead10ck** [comment]
Ah, it looks like openssl has made the default settings more strict, which is making the build host reject the key that the tests are making in memory. This should be a fixable problem though. I think when you see broken tests, the correct response is never to just delete the tests.

**Comment by johnward** [comment]
I agree. thanks
