### ISSUE TITLE
is this repo being maintained?

### ISSUE THREAD

**Issue by ravieze** [kafka-rust/kafka-rust#219]

**Comment by FaveroFerreira** [comment]
I don't think so.

**Comment by johnward** [comment]
I was maintaining it, but I my day job is simply too busy for me to put any meaningful time into this project at the moment. May try from September onwards.

**Comment by rtyler** [comment]
@johnward :wave: I've been keeping an eye on the repo from my corner of the world in [delta-rs](https://github.com/delta-io/delta-rs) and [kafka-delta-ingest](https://github.com/delta-io/kafka-delta-ingest).

A colleague of mine and I have been watching to see if kafka-rust might develop into a viable alternative to rust-rdkafka. What can we do to help jump in and clear the pull request queue and get things moving?

**Comment by johnward** [comment]
Hi, not really. I have been busy at a startup, but that has just finished so I have time again. I will have a look at the pull requests this week and get it moving. But I could definitely do with the help! John

**Comment by johnward** [comment]
I am very happy to receive contributions to the library, I am planning to push this forward now.
